### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by ffAudio**

### CODE REVIEW

**Comment by Werner88** [comment]
Hi Daniel,

thank you very much for this framework, I like it very much!!!


I have problems since your last update:

1)
a) after loading xml file, same after the first launch, the layout looks horrible
b) after changing the lookandfeel of a component (e.g. a slider) the layout looks horrible
after resizing everything is okay.

Maybe it has something to do with a missing call to 
builder->updateLayout(); 

2)
In windows the EqualizerExample is broken, no eq-lines are drawn.

3)
it is never possible to use the color names because whenever you click into a color field you are in the colourSelector.

I implemented this feature myself in a different way.
For the color fields I set the buttonText to „o“. Only after clicking the button the colourSelector launches.
The color field stays editable. When making the color field empty, the „0“ turns to an „x“. After clicking the „x“ you get the node.removeProperty call.
Anyway, it would be nice to have the color fields editable like before.



kind regards
and again thank you for guiMagic

Werner

**Comment by ffAudio** [comment]
Hi Werner,

Thanks for the feedback! That's much appreciated!

1)
Yes, I realised my mistake. By optimising away the recreation of the components the missing layout update became appearant. I created a fix yesterday on the develop branch and will merge it right away.

2)
I will have to look into that. As a one man team I forgot to test the windows. I only have a smoke test in my automatic builds.

Which eq-lines do you mean? The draggable lines or the frequency response?
Does it happen with a new plugin instance as well? Note that changes of the GUI are now persistent in that plugin instance. By opening a fresh instance, you will see the appearance, that a user will get.
And if you exported the XML, you still need to re-save the project to update the BinaryData.

3)
Indeed, i sacrificed the colour names. I need a way to bring them back. Unfortunately I don't like the idea of double meaning of the button. That one is meant to reset to the inherited value.
I will improve the colour picker anyway, it should have HSL sliders as well, and colour swatches to make it easier to copy colours over. Maybe a field to type the colour name there would be an option?
I think that feature needs a bit more thought, I am open for suggestions.

Cheers,
Daniel

**Comment by Werner88** [comment]
Hi Daniel,

thank you for your answer.

concerning point 3. why not having 2 buttons for a color field?
then you have the old behavior like before (editable + „x“ Button) and when you click the second button the colourSelector pops up

point 2.
the draggable lines are still there, the frequency responses are missing



I have some big wishes:

a)
 I need to customize the decorators paint method, right now I did not find a clean way to do this.
Is there a „official“ way that you had in mind?

 I experimented with something like this:
-inherit decorator not from component but from juce::GroupComponent
-give VIEW-Node some settableProperties like lookAndFeel (and some variables to be used in the LF-paint call)
so you can choose to select your own lookAndFeel for the Decorators paint method meanwhile the fallback is like it is right now

b)
right now you can change colors from a single component, this is fantastic
but also it would be great to change the colors of many components at once

here is a rough suggestion:
having a separate section in the editor maybe named for example „LookAndFeel-Colors“ or „Global-Colors“:
in this section you can choose a  lookAndFeel to be edited, next you have a ChoiceProperty field where
you can choose for example GroupComponent::BackgroundColor or Slider::ThumbColor and so on,
next a ColourProperty field to set the color (including a colourSelector)
if the values are not set individual and the component is set to the same LF then all the colors of all components in the Gui change at once,
this section should have a separate way to store and load „color-presets“

This brings two big advantages: you can change  and test new colors immediately, no need for a boring change in maybe 50 components,
and you can easily implement a way to change the whole color design (skin).  

This would be very great and improve the design possibilities and the speed of this great framework
Sorry for this rough draft. If it is not clear please let me know and I will try to explain it better.


Mit freundlichen Grüßen 
Werner Oestringer 


werner.oestringer@gmx.de

**Comment by Werner88** [comment]
Hi Daniel,

I just want to tell you that EqualizerExample is not broken. I had problems with the audio interface in the StandAloneApp.
(I had to change the settings for the input away from 24bit, then it worked) Sorry, it took a while for me to find out.

Concerning the customization - suggestion from my last mail (point a):
I think a clean way could be:

the lookAndFeel in the Decorator section should set only the Decorators paint (foleys or a custom one)
and there should be a lookAndFeel-choice in the components section (e.g. a slider) which sets the paint of the component

This way it would be a clear design, the LF is set where it belongs to, and everybody can customize it.

…and colour swatches is a great idea.


kind regards
Werner Oestringer

**Pull request merged**
